version: "3"
services:
  database:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    ports:
      - 5432:5432
    volumes:
      - "./database:/var/lib/postgresql/data/"

  test-database:
    image: postgres:alpine
    container_name: postgres-test
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
    ports:
      - 9090:5432

volumes:
  database:
