GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDc5ODUxODUsImV4cCI6MTY0Nzk4NTIwMCwiYXVkIjoiNjIzOGUxNGM3MjI2NjVmNWY2M2I5M2FmIiwiaXNzIjoic29tZXBhZ2UuY29tIn0.6xvwczlJ5M8di_zPFRIS_tEXWTK4Z3ZeFxhTuTvOaTU


### 404 Route
GET http://localhost:3000/teste


### Login Route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "Fletcher@hotmail.com",
  "password": "Fletcher"
}

### Register Route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "Fletcher@hotmail.com",
  "password": "Fletcher"
}

### Refresh Route
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
  "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDgwNzAxNDYsImV4cCI6MTY3OTYyNzc0NiwiYXVkIjoiNjIzOGUxNGM3MjI2NjVmNWY2M2I5M2FmIiwiaXNzIjoic29tZXBhZ2UuY29tIn0.3XZuydqmk7Iv4hdQaMbqtJr0eEaKztEk2qaxB-S1-Q4"
}

### logout Route
DELETE  http://localhost:3000/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDgwNzA4MjMsImV4cCI6MTY3OTYyODQyMywiYXVkIjoiNjIzOGUxNGM3MjI2NjVmNWY2M2I5M2FmIiwiaXNzIjoic29tZXBhZ2UuY29tIn0.Faw5c4Gpx2XoigsZlBGIUWgDUjvsGcPWb_dj3cIYmJg"
}