GET http://localhost:3000/all



### Adicionar Amigos
POST http://localhost:3000/add
Content-Type: application/json

{
  "friendName" : "Rafael de cesário",
  "likes" : "Gostos teste",
  "notes": "test notes",
  "birthday": "01/03",
  "personality" : "teste02",
  "presents" : "teste presents"
}


### Procurar por amigos
POST   http://localhost:3000/find
Content-Type: application/json

{
  "id" : "6250c4ac6f05e1b2d3dd03fd"
}


### Deletar Amigos
DELETE  http://localhost:3000/del
Content-Type: application/json

{
  "id" : "6250c8b16f05e1b2d3dd041e"
}


### Filtrar Amigos
POST http://localhost:3000/filter
content-type: application/json

{
  "friendName": "Rafael"
}


### Update dados amigos
PUT http://localhost:3000/update
Content-Type: application/json

{
  "id": "6254b4c36d75719c4c129465",
  "likes": "Gosto de tudo",
}