### Criar caderno
POST http://localhost:3000/notebooks
Content-Type: application/json

{
  "name" : "Programação",
  "pages": {
    "pagina01,clique aqui para alterar o nome" : "Teste"
  }
}


### alterar notas
PATCH  http://localhost:3000/notebooks/1
Content-Type: application/json

{
  "pages" : {
  "01" : "test"
  }
}


### mudar cores favoritas
PATCH  http://localhost:3000/notebooks/1
Content-Type: application/json

{
  "favColors" : []
}


### todos cadernos
GET http://localhost:3000/notebooks/1
Content-Type: application/json
